### ISSUE TITLE
Getting Scala library error

### ISSUE THREAD

**Issue by robvadai** [zladovan/gradle-avrohugger-plugin#2] opened 2020-03-08 12:59 UTC
Error message: `Scala library dependency was not found. Avrohugger plugin will use by default `2.11.0-M1` for check if scala version is below 2.11.`

Using Gradle 6.2.1 and Scala 2.12.10

As a result I can still run my build but the gradle-scoverage plugin breaks, due to incompatible Scala libraries on the classpath.

**Comment by zladovan** [comment] 2020-03-08 20:55
Hi,

The error message you've got is actually only warning. I found out there was a bug. It's already fixed in `0.4.2`. Thanks for for your input.

Unfortunately this will not solve your issue as it does not affect which scala version is used.

I made a quick test with `gradle-scoverage` in version `4.0.1` (latest for now) and I was able to generate report. 

Which version of `gradle-scoverage` do you use ?

**Comment by robvadai** [comment] 2020-03-08 21:39
Hi there,

I'm using version `4.0.1` too but I also use the `id 'com.adtran.scala-multiversion-plugin' version '1.0.35'` plugin, maybe when the Scala library is dynamically loaded the Avrohugger library has an issue?

Would you be able to post your `build.gradle` configuration that works with `scoverage`? Just so I can take a look for reference.

Thanks

**Comment by zladovan** [comment] 2020-03-08 22:04
I have used following build config form my test

```gradle
plugins {
    id 'scala'
    id 'com.zlad.gradle.avrohugger' version '0.4.2'
    id 'org.scoverage' version '4.0.1'
}

repositories {
   mavenCentral()
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.12.10'
}
```

I will make some tests with `com.adtran.scala-multiversion-plugin` meanwhile.

**Comment by zladovan** [comment] 2020-03-08 23:02
So I tried to test it with `com.adtran.scala-multiversion-plugin` and I think I was able to reproduce your issue.

I used following build config
```gradle
plugins {
    id 'scala'
    id 'com.zlad.gradle.avrohugger' version '0.4.2'
    id 'org.scoverage' version '4.0.1'
    id 'com.adtran.scala-multiversion-plugin' version '1.0.35'
}

repositories {
   mavenCentral()
}

dependencies {
    implementation 'org.scala-lang:scala-library:%scala-version%'
}
```

After running `./gradlew clean build reportScoverage -PscalaVersions=2.12.10` I got 

```
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
```
Is it what you are getting too ?

I tried without `gradle-avrohugger` and build was fine. I will try to look for some solution tomorrow.

**Comment by robvadai** [comment] 2020-03-12 19:48
Yep, this is the error I got. Thank you for looking into it.

**Comment by zladovan** [comment] 2020-03-16 22:47
I was not able to reproduce this issue again. I tried several times the scenario I posted before even with different scala versions, restarting gradle daemon and cleaning gradle caches but report was always generated successfully. I cannot figure out what have I done differently before. 

Could you share your build script, repsectively some minimalized version which is failing  with mentioned error ?

Or if it can be reduced to the same as I posted could you share more info about your environment like OS type, JDK version and exact gradle call ? 

Or any other idea ?

**Comment by titaniumcoder** [comment] 2020-05-05 08:56
I don't know if it matches but I have the issue in a multi-project build. We build from the same code a Java and a Scala module (multiple actually also with the scala-multiversion-plugin mentioned above) and then it happens.

Question is, whether it would be possible to just allow this detection algorithm to be overwritten by a setting in the gradle build. Because at least here we don't have Scala 2.10 at all. I will later check whether I quickly make a pull request, just need to upgrade my gradle plugin development knowledge first ;)

**Comment by zladovan** [comment] 2020-05-05 10:25
The detection algorithm is not cause of the issue. It's just small logic in groovy (not in scala) to set one flag. 

I think the problem is that version of underlying `avrohugger` library is using scala 2.12 and when `scala-multiversion-plugin` is used with different scala version there is some conflict. 

Ideally `gradle-avrohugger-plugin` should choose different version of `avrohugger` based on actual scala version set by `scala-multiversion-plugin`. Now I am not sure if it will be possible without having multiple versions (per each scala version) of `gradle-avrohugger-plugin` itself. 

Unfortunately there is probably some "random"  factor (maybe order of scala libraries on classpath) and I was not able to reproduce this issue again. So It would help me if  you @titaniumcoder could share some failing example project.

**Comment by titaniumcoder** [comment] 2020-05-05 10:51
@zladovan I will try to reproduce it in a smaller example this evening.

**Comment by titaniumcoder** [comment] 2020-05-05 12:35
@zladovan There you go: https://github.com/titaniumcoder/avrohugger-sample-issue-2 -- 

hoping it works, I didn't get the warning in that sample to work, but that could just be my gradle setup at the moment. So I checked over the case class which was not there.

Ignore directory java-library ( I just kept it to make sure I copy the whole multi-project logic)

scala-library-case-classes: I would expect a case class, but get a class (with multi-scala-version plugin)
scala-libra-case-hard213: here I hard code the scala version and then it works

I guess the "%scala-version%" is evaluated after the detection of the scala 2.12 version. I didn't do too many tests currently.

**Comment by zladovan** [comment] 2020-05-05 13:20
@titaniumcoder  I see now. Your case is something different as the original issue. I will create new issue for it and I will fix it.

Meanwhile you can downgrade `gradle-avrogugger-plugin` to `0.4.0` and it should work.

**Comment by titaniumcoder** [comment] 2020-05-05 13:32
No, I just see the warning now again. But still the same issue.

**Comment by titaniumcoder** [comment] 2020-05-05 13:33
Yes, seems to work for me. Now I also get the warning, but the case classes are there... which is strange.

**Comment by zladovan** [comment] 2020-05-05 13:36
@titaniumcoder  I made a fix in `0.4.2` for that warning message, but it looks it had some "side effects" :D

**Comment by titaniumcoder** [comment] 2020-05-05 15:21
Groovy side-effect free programming... that could be a challenge ;)

**Comment by robvadai** [comment] 2020-05-24 16:12
Version `0.4.4` works, thank you for updating it!
I'm happy for this issue to be closed.

**Closed as completed** 2020-05-24 18:24 UTC
